#!/usr/bin/env node
// Assembles L3 guidance from part files and generates data/comprehensive-guidance-l3.js
const fs = require('fs'), path = require('path');

// Load L3 control metadata
const src = fs.readFileSync(path.join(__dirname,'..','data','nist-800-172a.js'),'utf8');
const fn = new Function(src.replace(/^const\s+/gm,'var ').replace(/if\s*\(typeof\s+window\b.*$/s,'') + '\nreturn NIST_800_172A_FAMILIES;');
const families = fn();

// Build control map: nistId -> {name, req, cmmc}
const controlMap = {};
families.forEach(f => f.controls.forEach(c => {
    controlMap[c.id] = { name: c.name, req: c.requirement.substring(0,150), cmmc: c.cmmcPracticeId };
}));

// Load compact data from parts
const D1 = require('./gen-l3-part1.js');
const D2 = require('./gen-l3-part2.js');
const D = Object.assign({}, D1, D2);

// Provider name mapping
const providerNames = {
    aws: 'aws', azure: 'azure', gcp: 'gcp',
    pa: 'paloalto', s1: 'sentinelone', ninja: 'ninjaone', ten: 'tenable'
};
const sectionMap = {
    aws: 'cloud', azure: 'cloud', gcp: 'cloud',
    pa: 'firewalls', s1: 'xdr_edr', ninja: 'rmm', ten: 'vuln_mgmt'
};

// Expand compact format to full guidance format
function expand(nistId, compact) {
    const ctrl = controlMap[nistId];
    if (!ctrl) { console.warn('No control for', nistId); return null; }
    
    const obj = { summary: `Enhanced: ${ctrl.name} - ${ctrl.req}` };
    
    for (const [key, data] of Object.entries(compact)) {
        const section = sectionMap[key];
        const provider = providerNames[key];
        if (!section || !provider) continue;
        
        if (!obj[section]) obj[section] = {};
        
        const impl = {
            steps: data.st,
            verification: [
                `Verify ${ctrl.name.toLowerCase()} controls meet enhanced (L3) requirements`,
                `Review audit logs and configuration evidence for compliance`,
                `Test automated controls are functioning correctly`
            ],
            cost_estimate: data.cost,
            effort_hours: data.hrs
        };
        if (data.cli) impl.cli_example = data.cli;
        
        obj[section][provider] = {
            services: data.svc,
            implementation: impl
        };
    }
    
    return obj;
}

// Build objectives
const objectives = {};
let count = 0;
for (const [nistId, compact] of Object.entries(D)) {
    const ctrl = controlMap[nistId];
    if (!ctrl) continue;
    const expanded = expand(nistId, compact);
    if (expanded) {
        objectives[ctrl.cmmc] = expanded;
        count++;
    }
}

// Write output
const output = `// Comprehensive Implementation Guidance - CMMC Level 3 (Enhanced Security Requirements)
// NIST SP 800-172A - ${count} controls with control-specific guidance
// Technologies: AWS GovCloud, Azure GCC High, GCP, Palo Alto, SentinelOne, NinjaOne, Tenable
// Auto-generated by scripts/gen-l3.js

const COMPREHENSIVE_GUIDANCE_L3 = {
    version: "1.0.0",
    lastUpdated: "${new Date().toISOString().split('T')[0]}",
    description: "Enhanced security guidance for CMMC Level 3 controls (NIST 800-172A)",
    objectives: ${JSON.stringify(objectives, null, 8)}
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { COMPREHENSIVE_GUIDANCE_L3 };
}

if (typeof window !== 'undefined') {
    window.COMPREHENSIVE_GUIDANCE_L3 = COMPREHENSIVE_GUIDANCE_L3;
    console.log('[L3 Guidance] Loaded -', Object.keys(COMPREHENSIVE_GUIDANCE_L3.objectives).length, 'controls');
}
`;

const outPath = path.join(__dirname, '..', 'data', 'comprehensive-guidance-l3.js');
fs.writeFileSync(outPath, output, 'utf8');
console.log(`Written ${outPath}`);
console.log(`Controls: ${count}`);
console.log(`File size: ${(output.length/1024).toFixed(1)} KB`);

// Validate syntax
try {
    delete require.cache[require.resolve(outPath)];
    const loaded = require(outPath);
    const keys = Object.keys(loaded.COMPREHENSIVE_GUIDANCE_L3.objectives);
    console.log('Syntax: VALID');
    console.log('Keys:', keys.join(', '));
    
    // Verify each key has expected sections
    let totalSections = 0;
    for (const [key, val] of Object.entries(loaded.COMPREHENSIVE_GUIDANCE_L3.objectives)) {
        const sections = ['cloud','firewalls','xdr_edr','rmm','vuln_mgmt'].filter(s => val[s]);
        totalSections += sections.length;
    }
    console.log(`Total technology sections: ${totalSections}`);
} catch (e) {
    console.error('Syntax ERROR:', e.message);
    process.exit(1);
}
